title: darkBlogger
email: insidedarkpit@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Blogs that **you** need.
  Here you will find tech, AI, Cloud. And anything which impact you as a developer.
baseurl: "" # the subpath of your site, e.g. /blog
tagline: A blog that you need.
url: "https://blog.darkraspberry.ga"
github_username:  darkRaspberry
twitter_username: devRaspberry
lang: en-US
content_lang: ''
timezone: Asia/Kolkata
# Notice that once it is assigned, the CDN url
# will be added to all image (site avatar & posts' images) paths starting with '/'
# e.g. 'https://cdn.com'
# img_cdn: ''

# the avatar on sidebar, support local or CORS resources
avatar: /assets/img/favicon.png

# boolean type, the global switch for ToC in posts.
toc: true # Table of contents

paginate: 5
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
github:
  username: darkRaspberry             # change to your github username

twitter:
  username: devRaspberry

social:
# Name will be displayed as the default author of the posts and the copyright owner in the Footer
  name: Abhay Kumar Verma
  email: insidedarkpit@gmail.com             # change to your email address
  links:
    - https://twitter.com/devRaspberry      # change to your twitter homepage
    - https://github.com/darkRaspberry       # change to your github homepage


# ------------ The following options are not recommended to be modified ------------------

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:   # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order


defaults:
  -
    scope:
      path: ''          # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true    # Enable comments in posts.
      toc: true         # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
  -
    scope:
      path: _drafts
    values:
      comments: false
  -
    scope:
      path: ''
      type: tabs             # see `site.collections`
    values:
      layout: page
      permalink: /:title/
      dynamic_title: true    # Hide title in mobile screens.

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false

exclude:
  - README.md
  - LICENSE

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

# Outdated configuration warning
outdated: '-- Missing configuration options! --'
